{
  "debug": false,
  "mode": "train",
  "cuda": true,
  "pin_memory": true,
  "wandb": true,
  "worker": 8,
  "log_interval": 100,
  "save_interval": 5,
  "saved_model_directory": "model_ckpts",
  "train_fold": 1,
  "project_name": "AMDNet",
  "CUDA_VISIBLE_DEVICES": "0",

  "model_name": "AMDNet",
  "n_classes": 1,
  "in_channels": 3,
  "dataloader": "Image2Image_zero_pad",
  "criterion": "DiceBCELoss",
  "task": "segmentation",
  "input_space": "RGB",
  "input_channel": 3,
  "input_size": [192, 192],
  "batch_size": 2,
  "optimizer": "AdamW",
  "lr": 0.001,
  "scheduler": "WarmupCosine",
  "cycles": 100,
  "warmup_epoch": 10,
  "weight_decay": 0.05,
  "epoch": 100,
  "ema_decay": 0.99,
  "class_weight": [1.0, 1.0],
  "model_path": "",
  "freeze_layer": false,

  "transform_blur": true,
  "transform_jitter": true,
  "transform_hflip": true,
  "transform_perspective": false,
  "transform_cutmix": true,
  "transform_rand_resize": true,
  "transform_rand_crop": 160,

  "train_x_path": "/content/FSG-Net-pytorch/dataset/DRIVE/train/input",
  "train_y_path": "/content/FSG-Net-pytorch/dataset/DRIVE/train/label",
  "val_x_path": "/content/FSG-Net-pytorch/dataset/DRIVE/val/input",
  "val_y_path": "/content/FSG-Net-pytorch/dataset/DRIVE/val/label"
}
