{
  "debug": False,
  "mode": "train",
  "cuda": True,
  "pin_memory": True,
  "wandb": False,
  "worker": 2,
  "log_interval": 100,
  "save_interval": 1,
  "saved_model_directory": "model_ckpts",
  "train_fold": 1,
  "project_name": "AMDNet",
  "CUDA_VISIBLE_DEVICES": "0",

  "model_name": "AMDNet",
  "n_classes": 1,
  "in_channels": 3,
  "dataloader": "Image2Image_zero_pad",
  "criterion": "DiceBCELoss",
  "task": "segmentation",
  "input_space": "RGB",
  "input_channel": 3,
  "input_size": [608, 608],
  "optimizer": "AdamW",
  "lr": 0.001,
  "scheduler": "WarmupCosine",
  "cycles": 100,
  "warmup_epoch": 20,
  "weight_decay": 0.05,
  "batch_size": 2,
  "epoch": 100,
  "ema_decay": 0,
  "class_weight": [1.0, 1.0],
  "model_path": "",
  "freeze_layer": False,

  "transform_blur": True,
  "transform_jitter": True,
  "transform_hflip": True,
  "transform_perspective": True,
  "transform_cutmix": True,
  "transform_rand_resize": True,
  "transform_rand_crop": 288,

  "train_x_path": "/content/FSG-Net-pytorch/dataset/DRIVE/train/input",
  "train_y_path": "/content/FSG-Net-pytorch/dataset/DRIVE/train/label",
  "val_x_path": "/content/FSG-Net-pytorch/dataset/DRIVE/val/input",
  "val_y_path": "/content/FSG-Net-pytorch/dataset/DRIVE/val/label"
}