{
### Environment Parameters
  debug: false
  mode: train
  cuda: true
  pin_memory: true
  wandb: false  # set false jika ada masalah autentikasi Wandb
  worker: 2  # direkomendasikan max 2 di Colab
  log_interval: 100
  save_interval: 1
  saved_model_directory: 'model_ckpts'
  train_fold: 1
  project_name: 'FSG-Net'
  CUDA_VISIBLE_DEVICES: '0'  # Colab hanya memiliki 1 GPU (GPU:0)
  ### Train Parameters
  model_name: 'FSGNet'
  n_classes: 1
  in_channels: 3
  dataloader: 'Image2Image_zero_pad'
  criterion: 'DiceBCELoss'
  task: 'segmentation'
  input_space: 'RGB'
  input_channel: 3
  input_size: [608, 608]  # sesuaikan dengan dataset DRIVE
  optimizer: 'AdamW'
  lr: 0.001
  scheduler: 'WarmupCosine'
  cycles: 100
  warmup_epoch: 20
  weight_decay: 0.05
  batch_size: 2  # Sesuaikan dengan memori GPU Colab
  epoch: 100  # ubah menjadi 100 atau sesuai kebutuhan
  ema_decay: 0
  class_weight: [1.0, 1.0]
  model_path: ''
  freeze_layer: false

  ### Augmentation Parameters
  transform_blur: true
  transform_jitter: true
  transform_hflip: true
  transform_perspective: true
  transform_cutmix: true
  transform_rand_resize: true
  transform_rand_crop: 288

  ### Paths (sesuaikan dengan struktur direktori di Colab)
  train_x_path: '/content/FSG-Net-pytorch/dataset/DRIVE/train/input'
  train_y_path: '/content/FSG-Net-pytorch/dataset/DRIVE/train/label'
  val_x_path: '/content/FSG-Net-pytorch/dataset/DRIVE/val/input'
  val_y_path: '/content/FSG-Net-pytorch/dataset/DRIVE/val/label'
}